### ISSUE TITLE
从github下载aira2证书验证失败

### ISSUE THREAD

**Issue by yiguoqi** [yuyumoko/otogi-frontier-updater#1]
旧版能用，改aira2之后就寄了  而且实际上我有配置aira下载器但更新程序它认不出来  命令提示符aria2c --version显示有安装也能正常使用   如下

INFO     [2024-11-17 14:50:19](DEBUG) -  未找到aria2c
INFO     [2024-11-17 14:50:19](DEBUG) -  正在获取最新aria2c版本
INFO     [2024-11-17 14:50:19](DEBUG) -  最新版本: 1.37.0
INFO     [2024-11-17 14:50:19](DEBUG) -  正在下载aria2c组件
ERROR    [2024-11-17 14:50:19](DEBUG) -  HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /aria2/aria2/releases/download/release-1.37.0/aria2-1.37.0-win-64bit-build1.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 466, in _make_request
  File "urllib3\connectionpool.py", line 1095, in _validate_conn
  File "urllib3\connection.py", line 730, in connect
  File "urllib3\connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
  File "urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
  File "ssl.py", line 517, in wrap_socket
  File "ssl.py", line 1108, in _create
  File "ssl.py", line 1379, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 490, in _make_request
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 667, in send
  File "urllib3\connectionpool.py", line 843, in urlopen
  File "urllib3\util\retry.py", line 519, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /aria2/aria2/releases/download/release-1.37.0/aria2-1.37.0-win-64bit-build1.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 382, in show_menu
  File "utils\menu_tools.py", line 71, in show
  File "main.py", line 199, in run_check_update
  File "asyncio\runners.py", line 190, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 653, in run_until_complete
  File "main.py", line 89, in check_update
  File "core\CheckUpdate.py", line 390, in check_game_update
  File "core\CheckUpdate.py", line 46, in init_chara_icon_cache
  File "utils\aria2c.py", line 83, in __init__
  File "utils\aria2c.py", line 64, in init_aria2c
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 698, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /aria2/aria2/releases/download/release-1.37.0/aria2-1.37.0-win-64bit-build1.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))

**Comment by yuyumoko** [comment]
项目的runtime里有现成的 可以先使用那个
